# Generated by Django 5.1.4 on 2025-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="photo",
        ),
        migrations.AddField(
            model_name="tweet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
